# -*- coding: utf-8 -*-
"""Lift the research questions, hypotheses and objectives out of the proposal into the repo.

    python scripts/extract_scope.py                 # write docs/RESEARCH-SCOPE.md
    python scripts/extract_scope.py --check         # fail if the file is out of date

The proposal is a `.docx`, which no test can read without a dependency this project does not
declare and which nothing else needs. So the proposal stays the source and this writes a tracked
plain-text copy of the parts the system has to agree with. `praxis/research/questions.py` is
held against that copy by `tests/unit/test_research_questions.py`, and the copy is held against
the proposal by running this with `--check`.

**Why not keep reading `thesis/02-refined-scope.md`.** That document describes an earlier design
in which the model trained on campus microteaching and was evaluated on basic-school classrooms.
The revised proposal moves the whole study into authentic teaching practicum and makes the shift
axis held-out schools and colleges instead of a change of domain. Six of the seven hypotheses
are reworded accordingly. Two documents stating different research questions is the drift this
is meant to make visible, so the one being tracked is named here and the other is recorded as
superseded.

The digest of the source document is written into the output. A revised proposal therefore shows
up as a digest mismatch rather than as nothing at all.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

PROPOSAL = REPO_ROOT / "PhD Proposal - Teaching Practicum Revised.docx"
OUTPUT = REPO_ROOT / "docs" / "RESEARCH-SCOPE.md"

# Tables are found by their header row, not by position. A reordered document would otherwise
# relabel hypotheses as objectives and the file would still look well formed.
WANTED = {
    ("#", "Objective"): "objectives",
    ("#", "Question"): "questions",
    ("#", "Hypothesis", "Direction"): "hypotheses",
    ("#", "Behaviour", "Observable definition", "Status"): "behaviours",
    ("Phase", "Work", "Definition of done"): "phases",
}

HEADINGS = {
    "objectives": "Specific objectives",
    "questions": "Research questions",
    "hypotheses": "Hypotheses",
    "behaviours": "Target behaviours",
    "phases": "Phases and definition of done",
}


def row_values(row) -> list[str]:
    """Cell text, with merged cells collapsed and newlines flattened."""
    out: list[str] = []
    for cell in row.cells:
        text = " ".join(cell.text.split())
        if not out or out[-1] != text:
            out.append(text)
    return out


def tables(path: Path) -> dict[str, list[list[str]]]:
    import docx

    document = docx.Document(str(path))
    found: dict[str, list[list[str]]] = {}
    for table in document.tables:
        rows = [row_values(row) for row in table.rows]
        if not rows:
            continue
        name = WANTED.get(tuple(rows[0]))
        if name is None:
            continue
        found[name] = rows

    missing = set(WANTED.values()) - set(found)
    if missing:
        raise SystemExit(
            f"{path.name} has no table whose header row matches {sorted(missing)}. The "
            f"proposal's table headers are what this script finds them by; if they were "
            f"reworded, update WANTED rather than guessing by position.")
    return found


def title_of(path: Path) -> str:
    import docx

    for paragraph in docx.Document(str(path)).paragraphs:
        text = paragraph.text.strip()
        if text and text.upper() == text and len(text) > 40:
            return text
    return "title not found"


def render(path: Path, found: dict[str, list[list[str]]]) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    lines = [
        "# Research scope of record",
        "",
        "Generated by `scripts/extract_scope.py` from the proposal named below. Do not edit by",
        "hand: run the script. `praxis/research/questions.py` declares the same questions in",
        "code and `tests/unit/test_research_questions.py` holds the two together, so a",
        "question this file states and the system does not is a failing test rather than a",
        "silent gap.",
        "",
        f"**Source.** `{path.name}`",
        "",
        f"**Digest.** `sha256:{digest}`",
        "",
        "**Superseded.** `thesis/02-refined-scope.md` sections 3 and 6 describe the earlier",
        "design in which the model trained on campus microteaching and was evaluated on",
        "basic-school classrooms. The revised proposal places the whole study in authentic",
        "teaching practicum and makes the shift axis held-out schools and colleges. Where the",
        "two disagree, this file is the one the system is built against.",
        "",
        f"**Title.** {title_of(path)}",
    ]

    for name in ("questions", "hypotheses", "objectives", "behaviours", "phases"):
        rows = found[name]
        lines += ["", "---", "", f"## {HEADINGS[name]}", ""]
        header, *body = rows
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join("---" for _ in header) + "|")
        for row in body:
            padded = row + [""] * (len(header) - len(row))
            lines.append("| " + " | ".join(padded[:len(header)]) + " |")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the tracked copy is not what the proposal says")
    parser.add_argument("--proposal", type=Path, default=PROPOSAL)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    if not args.proposal.is_file():
        print(f"error: no proposal at {args.proposal}", file=sys.stderr)
        return 2

    rendered = render(args.proposal, tables(args.proposal))

    if args.check:
        if not args.output.is_file():
            print(f"error: {args.output.name} does not exist; run without --check",
                  file=sys.stderr)
            return 1
        current = args.output.read_text(encoding="utf-8")
        if current != rendered:
            print(f"error: {args.output.name} is out of date with {args.proposal.name}. "
                  f"Run scripts/extract_scope.py and review the diff.", file=sys.stderr)
            return 1
        print(f"{args.output.name} matches {args.proposal.name}")
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output.relative_to(REPO_ROOT)} from {args.proposal.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
