# -*- coding: utf-8 -*-
"""Write constraints.generated.txt: every project package pinned to its installed version.

D41 says a pin nobody has run is a guess, and installing from a guess is how a reproducible run
stops being reproducible. A plain `uv pip compile` resolves against whatever PyPI offers on the
day it runs, which is how requirements.lock came to pin forty transitive packages at versions
the suite had never executed - starlette 1.7.0 against the 1.3.1 the media endpoint's range
tests were written on, among them. Compiling the lock with these constraints makes it record the
environment the suite actually passed in.

    python scripts/freeze_constraints.py
    python -m uv pip compile requirements.txt --universal --generate-hashes \
        --constraint constraints.generated.txt -o requirements.lock

Only packages already named in requirements.lock are pinned, and only those whose markers apply
to the running platform. The interpreter here is shared with other projects, so a blanket
`pip freeze` would drag their dependencies into this one's lock; and a package the lock marks
linux-only is not installed on a Windows machine, so there is no measured version to pin it to.
Those stay unconstrained and resolve freely, which is correct: the claim being made is about
what ran, and they did not run.
"""
from __future__ import annotations

import re
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from packaging.markers import Marker

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK = REPO_ROOT / "requirements.lock"
OUT = REPO_ROOT / "constraints.generated.txt"

# `name==version` optionally followed by `; marker`, with uv's trailing backslash.
PINNED = re.compile(r"^([A-Za-z0-9._-]+)==([^ ;\\]+)\s*(?:;\s*(.*?))?\s*\\?$")

# Declared in requirements.txt but absent from the lock until it is next compiled. Without this
# the first run after a dependency is added leaves it unpinned, and the lock records a version
# that was never measured - the whole failure this script exists to prevent.
EXTRA = ("pytest-randomly", "pytest-xdist", "execnet")

HEADER = """\
# GENERATED by scripts/freeze_constraints.py. Do not edit by hand.
#
# Every package requirements.lock names, pinned to the version installed on the machine the
# suite was measured on. requirements.lock is compiled against this file so that it records what
# ran rather than what resolves today. See D41 and the script's docstring.
"""


def applicable_packages(lock_text: str) -> set[str]:
    """Package names in the lock whose environment markers hold on this platform."""
    found = set()
    for line in lock_text.splitlines():
        if not line or line[0] in " #":
            continue
        match = PINNED.match(line.rstrip())
        if match is None:
            continue
        marker = match.group(3)
        if marker and not Marker(marker).evaluate():
            continue
        found.add(match.group(1).lower().replace("_", "-"))
    return found


def main() -> int:
    if not LOCK.is_file():
        print(f"error: {LOCK.name} does not exist, so there is nothing to constrain",
              file=sys.stderr)
        return 1

    wanted = applicable_packages(LOCK.read_text(encoding="utf-8")) | set(EXTRA)

    pins, absent = [], []
    for name in sorted(wanted):
        try:
            pins.append(f"{name}=={version(name)}")
        except PackageNotFoundError:
            absent.append(name)

    OUT.write_text(HEADER + "\n".join(pins) + "\n", encoding="utf-8")
    print(f"{OUT.name}: {len(pins)} packages pinned to their installed versions")
    if absent:
        print(f"  left unconstrained, not installed here: {', '.join(absent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
