# -*- coding: utf-8 -*-
"""Run the whole system on a synthetic corpus, in a scratch database, and report what happened.

    python scripts/verify_end_to_end.py
    python scripts/verify_end_to_end.py --keep          # leave the scratch database behind
    python scripts/verify_end_to_end.py --sessions 4

This exists to answer one question: does the system work end to end on this machine? It builds
a corpus from nothing, puts it through every phase the real corpus would go through, and
prints which phases ran, which abstained and why.

**What it proves and what it does not.** It proves the pipeline executes: that ingest writes
sessions, that the quality gate judges them, that preprocessing extracts pose and destroys the
original, that the audit chain verifies, that the API answers, and that every phase either
does its work or says what it is missing. It proves *nothing* about teaching-behaviour
detection. The clips are generated by ffmpeg and contain no teacher, no learner and no
behaviour, so every artefact this writes is stamped `infrastructure_validation: true`. A
number measured here is a property of the plumbing and may never be reported as a result.

**It touches nothing real.** A fresh database created and dropped per run, a scratch media
root under `paths.scratch`, and a scratch config. The research database, the real corpus and
`configs/default.yaml` are not read for anything but a template and are never written.

Two gate settings are relaxed for synthetic footage, and the report says so: the duration
floor, because generating 40 seconds of video per session to clear a floor about behaviour
episodes wastes minutes to prove nothing, and the person-presence fraction, because `testsrc`
contains no person. Every other check runs as configured. The real corpus is where the gate is
exercised for real.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import yaml
from sqlalchemy import func, select

from praxis.config import load_config
from praxis.db import build_engine, transaction
from praxis.db.schema import (
    colleges,
    consent_records,
    media_objects,
    pose_artifacts,
    sessions,
    teachers,
)
from praxis.ids import new_ulid
from praxis.tools import resolve
from scripts.verify_audit_chain import HEAD_PREFIX

RAN, FAILED, ABSTAINED = 0, 1, 3
MANIFEST_HEADER = ("filename,teacher_code,college_code,domain,recorded_on,subject,grade_level,"
                   "camera_distance_m,room_area_m2,pupil_count,ambient_noise_dba,"
                   "teacher_movement_range_m\n")


class VerificationFailed(RuntimeError):
    """A step that had to work did not. Distinct from a phase that abstained."""


# ---------------------------------------------------------------------------
# the scratch environment
# ---------------------------------------------------------------------------

def _admin_dsn(dsn: str) -> str:
    return re.sub(r"dbname=\S+", "dbname=postgres", dsn)


def _dsn_from_dev_services() -> str:
    """The local cluster's DSN, via the script that already knows how to print it."""
    done = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "dev_services.py"), "dsn"],
        capture_output=True, text=True, stdin=subprocess.DEVNULL)
    if done.returncode != 0:
        raise VerificationFailed(
            f"could not get a database DSN: {done.stderr.strip() or done.stdout.strip()}. "
            f"Start the cluster with: python scripts/dev_services.py start")
    match = re.search(r'export PRAXIS_TEST_DSN="([^"]+)"', done.stdout)
    if not match:
        raise VerificationFailed(
            f"dev_services.py dsn printed something unexpected: {done.stdout}")
    return match.group(1)


def create_database(dsn: str) -> tuple[str, str]:
    """A fresh database, migrated. Returns its keyword DSN and its SQLAlchemy URL."""
    import psycopg

    name = f"praxis_verify_{new_ulid()[-12:].lower()}"
    scratch = re.sub(r"dbname=\S+", f"dbname={name}", dsn)
    parts = dict(piece.split("=", 1) for piece in scratch.split())
    url = (f"postgresql+psycopg://{parts['user']}:{parts['password']}"
           f"@{parts['host']}:{parts['port']}/{name}")

    with psycopg.connect(_admin_dsn(dsn), autocommit=True) as conn:
        conn.execute(f'CREATE DATABASE "{name}"')

    applied = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"], cwd=REPO_ROOT,
        capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=300,
        env={**_env(), "DATABASE_URL": url})
    if applied.returncode != 0:
        raise VerificationFailed(f"could not migrate {name}:\n{applied.stderr}")
    return scratch, url


def drop_database(dsn: str, scratch: str) -> None:
    import psycopg

    name = dict(piece.split("=", 1) for piece in scratch.split())["dbname"]
    with psycopg.connect(_admin_dsn(dsn), autocommit=True) as conn:
        conn.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                     "WHERE datname = %s AND pid <> pg_backend_pid()", (name,))
        conn.execute(f'DROP DATABASE IF EXISTS "{name}"')


def _env() -> dict[str, str]:
    import os
    return dict(os.environ)


def write_config(template: Path, destination: Path, root: Path, *,
                 manifest: Path, media_dir: Path, keymap: Path) -> Path:
    """A scratch config: the real one with every path pointed inside `root`.

    Read as raw YAML and not through `load_config`, because the template carries `${VAR}`
    placeholders that must be replaced with literal scratch paths rather than resolved from an
    environment this run does not control.
    """
    raw = yaml.safe_load(template.read_text(encoding="utf-8"))

    def as_posix(path: Path) -> str:
        return path.resolve().as_posix()

    raw["paths"].update({
        "media_root": as_posix(root / "media"),
        "feature_cache": as_posix(root / "features"),
        "pose_artifacts": as_posix(root / "pose"),
        "run_outputs": as_posix(root / "runs"),
        "scratch": as_posix(root / "tmp"),
        "torch_home": as_posix(root / "torch"),
    })
    raw["ingest"].update({
        "manifest": as_posix(manifest),
        "media_dir": as_posix(media_dir),
        "keymap": as_posix(keymap),
    })
    # One relaxation, and it is reported as one. `testsrc` contains no person, so the presence
    # fraction is the single check synthetic footage cannot pass. The duration floor is NOT
    # lowered: `the_duration_floor_admits_enough_clips` refuses a floor under five clips, and it
    # is right to, so the clips are generated long enough to clear it for real.
    raw["ingest"]["quality_gate"]["min_person_present_fraction"] = 0.0
    raw["run"]["name"] = "verification"

    for key in ("media", "features", "pose", "runs", "tmp", "torch"):
        (root / key).mkdir(parents=True, exist_ok=True)
    destination.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")
    return destination


# ---------------------------------------------------------------------------
# the synthetic corpus
# ---------------------------------------------------------------------------

def make_clip(ffmpeg, path: Path, seconds: float, *, colour: str) -> Path:
    """One clip. `colour` differs per session so no two are byte-identical and deduplicated."""
    path.parent.mkdir(parents=True, exist_ok=True)
    argv = [
        "-y",
        "-f", "lavfi", "-i", f"color=c={colour}:size=640x480:rate=25:duration={seconds}",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
        "-c:a", "aac", "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        str(path),
    ]
    done = subprocess.run(ffmpeg.command("-v", "error", *argv, file_only=False),
                          capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=300)
    if done.returncode != 0 or not path.is_file():
        raise VerificationFailed(f"ffmpeg could not build {path.name}: {done.stderr.strip()}")
    return path


COLOURS = ("red", "green", "blue", "yellow", "magenta", "cyan", "orange", "purple")


def build_corpus(root: Path, ffmpeg, count: int, seconds: float) -> tuple[Path, Path]:
    """Synthetic footage plus the manifest naming it. One session per teacher."""
    incoming = root / "incoming"
    rows = []
    for index in range(count):
        name = f"session-{index + 1:02d}.mp4"
        make_clip(ffmpeg, incoming / name, seconds, colour=COLOURS[index % len(COLOURS)])
        rows.append(
            f"{name},T-{index + 1:02d},COE-V,microteaching,2026-03-{index + 1:02d},"
            f"science,JHS2,3.5,48,31,52,4.2\n")

    manifest = root / "sessions.csv"
    manifest.write_text(MANIFEST_HEADER + "".join(rows), encoding="utf-8")
    return manifest, incoming


def seed_consents(url: str, keymap: Path) -> int:
    """One live consent per teacher in the key file, so ingest has a basis to proceed.

    The real path for this is `scripts/import_consents.py`, which requires a document reference
    naming a signed form. Here the subjects are synthetic and the reference says so: a
    verification run must not leave a row that could be mistaken for evidence of real consent.
    """
    import csv

    with keymap.open(newline="", encoding="utf-8-sig") as handle:
        pairs = [(row["teacher_code"], row["teacher_id"], row["college_id"])
                 for row in csv.DictReader(handle)]
    if not pairs:
        raise VerificationFailed(f"{keymap} has no teacher rows; identifier minting failed")

    engine = build_engine(url)
    with transaction(engine) as conn:
        for code, teacher_id, college_id in pairs:
            conn.execute(consent_records.insert().values(
                consent_id=new_ulid(), subject_type="teacher", teacher_id=teacher_id,
                college_id=college_id,
                purpose="SYNTHETIC infrastructure verification, not research",
                recipients="nobody; this corpus is generated and contains no person",
                scope="both", granted_on=date(2026, 1, 1),
                document_ref=f"SYNTHETIC/verification/{code}", created_at=func.now()))
    return len(pairs)


# ---------------------------------------------------------------------------
# running it
# ---------------------------------------------------------------------------

def run_script(script: str, *argv: str, env: dict[str, str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / script), *argv],
        capture_output=True, text=True, stdin=subprocess.DEVNULL, cwd=REPO_ROOT, env=env)


def phase_results(run_outputs: Path) -> list[dict[str, object]]:
    """Every run under `run_outputs`, newest first, with its verdict."""
    found = []
    for directory in sorted(run_outputs.iterdir(), reverse=True):
        manifest, result = directory / "manifest.json", directory / "result.json"
        if not (directory.is_dir() and manifest.is_file() and result.is_file()):
            continue
        man = json.loads(manifest.read_text(encoding="utf-8"))
        res = json.loads(result.read_text(encoding="utf-8"))
        found.append({
            "phase": man.get("phase"), "run_id": man.get("run_id"),
            "ran": bool(res.get("ran")),
            "abstained": (res.get("abstained") or {}).get("reason"),
            "missing": (res.get("abstained") or {}).get("missing") or [],
            "artefacts": len(man.get("artefacts") or []),
            "summary": {k: v for k, v in res.items()
                        if k not in ("ran", "abstained", "artefacts")},
        })
    return found


def check_database(url: str) -> dict[str, object]:
    """What actually landed. These are the assertions, not a progress report."""
    engine = build_engine(url)
    with transaction(engine) as conn:
        counts = {
            name: conn.execute(select(func.count()).select_from(table)).scalar_one()
            for name, table in (("colleges", colleges), ("teachers", teachers),
                                ("consent_records", consent_records), ("sessions", sessions),
                                ("media_objects", media_objects),
                                ("pose_artifacts", pose_artifacts))
        }
        verdicts = dict(conn.execute(
            select(sessions.c.quality_verdict, func.count())
            .group_by(sessions.c.quality_verdict)).all())
        blurred = conn.execute(
            select(func.count()).select_from(media_objects)
            .where(media_objects.c.is_blurred.is_(True))).scalar_one()
    return {"counts": counts, "quality_verdicts": verdicts, "blurred_media": blurred}


def check_api(url: str, config_path: Path, media_root: Path) -> dict[str, object]:
    """The API answers against this corpus. Built through the factory, not the entry point."""
    from fastapi.testclient import TestClient

    from praxis.api.app import create_app

    app = create_app(config=load_config(config_path), engine=build_engine(url),
                     media_root=media_root, enqueue=lambda _session_id: None)
    client = TestClient(app)
    answers = {}
    for name, path in (("health", "/api/v1/health"),
                       ("summary", "/api/v1/dashboard/summary"),
                       ("sessions", "/api/v1/dashboard/sessions?limit=50")):
        response = client.get(path)
        answers[name] = response.status_code
        if response.status_code != 200:
            raise VerificationFailed(f"{path} answered {response.status_code}: {response.text}")
        if name == "sessions":
            answers["sessions_listed"] = len(response.json().get("sessions", []))
    return answers


def check_audit_chain(env: dict[str, str]) -> str:
    """The hash chain verifies. R5's whole point, checked by the script that owns it.

    `--from-db` and not a JSON export, because the chain this build wrote is in the scratch
    database and nothing has exported it. The argument was missing entirely until now, so the
    verifier exited 2 on its own usage message and the harness read that as a broken chain:
    every run of this script ended in "VERIFICATION FAILED: the audit chain does not verify"
    with the eleven phases underneath it reporting no failures at all. The chain was never
    checked, and the one check that would have said so was the one that could not run.
    """
    done = run_script("verify_audit_chain.py", "--from-db", env=env)
    if done.returncode != 0:
        raise VerificationFailed(
            f"the audit chain does not verify:\n{done.stdout}\n{done.stderr}")
    return reported_head(done.stdout)


def reported_head(stdout: str) -> str:
    """The head hash the verifier printed, or a statement that there is no head.

    This took the last line of stdout, which is the head only when the chain has rows in it. An
    empty chain prints one line - "empty. An empty chain is intact and proves nothing." - and
    that sentence went into the report's `audit_chain` field, under a heading that reads "audit
    chain" and alongside a hash in every other run. A field that holds a hash most of the time
    and a sentence the rest of the time is one a reader will quote as a hash.

    An empty chain is not a failure: the verifier exits 0 and is right to, and D48 makes an
    unavailable check abstain rather than fail. What it must not do is look like a verified
    head. So it is named as what it is.
    """
    for line in stdout.strip().splitlines():
        if line.startswith(HEAD_PREFIX):
            return line
    return "no head: the audit log is empty, which is intact and proves nothing"


# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sessions", type=int, default=6,
                        help="synthetic sessions, one teacher each (default 6, the minimum "
                             "that can make three teacher-disjoint partitions)")
    parser.add_argument("--seconds", type=float, default=42.0,
                        help="length of each synthetic session; must clear the real duration "
                             "floor, which is MIN_USEFUL_CLIPS x behaviour.clip.length_s")
    parser.add_argument("--keep", action="store_true",
                        help="leave the scratch database and files in place")
    parser.add_argument("--config", type=Path, default=REPO_ROOT / "configs" / "default.yaml",
                        help="the template to derive the scratch config from")
    args = parser.parse_args(argv)

    template = load_config(args.config)
    ffmpeg = resolve("ffmpeg", template.tools.ffmpeg)
    root = Path(template.paths.scratch) / f"verify-{new_ulid()[-10:].lower()}"
    root.mkdir(parents=True, exist_ok=True)

    print(f"verification run in {root}")
    print("  synthetic corpus, scratch database, nothing real is touched\n")

    dsn = _dsn_from_dev_services()
    scratch_dsn, url = create_database(dsn)
    name = dict(piece.split("=", 1) for piece in scratch_dsn.split())["dbname"]
    print(f"  database   {name} created and migrated")

    started = time.monotonic()
    report: dict[str, object] = {"infrastructure_validation": True, "root": str(root)}
    try:
        manifest, incoming = build_corpus(root, ffmpeg, args.sessions, args.seconds)
        print(f"  corpus     {args.sessions} synthetic sessions in {incoming.name}/")

        keymap = root / "keys.csv"
        config_path = write_config(args.config, root / "config.yaml", root,
                                   manifest=manifest, media_dir=incoming, keymap=keymap)
        env = {**_env(), "DATABASE_URL": url,
               "PRAXIS_MEDIA_ROOT": str((root / "media").resolve())}

        mint = run_script("ingest_corpus.py", "--config", str(config_path),
                          "--manifest", str(manifest), "--media-dir", str(incoming),
                          "--keymap", str(keymap), "--create-missing", "--dry-run", env=env)
        if not keymap.is_file():
            raise VerificationFailed(
                f"identifier minting wrote no key file:\n{mint.stdout}\n{mint.stderr}")
        granted = seed_consents(url, keymap)
        print(f"  consent    {granted} synthetic consent records, marked SYNTHETIC")

        build = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "run_build.py"),
             "--config", str(config_path)],
            capture_output=True, text=True, stdin=subprocess.DEVNULL, cwd=REPO_ROOT, env=env)
        sys.stdout.write(build.stdout)
        if build.returncode not in (RAN, ABSTAINED):
            raise VerificationFailed(f"the build failed:\n{build.stderr[-2000:]}")

        phases = phase_results(root / "runs")
        report["phases"] = phases
        report["database"] = check_database(url)
        report["api"] = check_api(url, config_path, root / "media")
        report["audit_chain"] = check_audit_chain(env)
        report["seconds"] = round(time.monotonic() - started, 1)

        (root / "verification.json").write_text(
            json.dumps(report, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
        _print_report(report)
        return RAN

    except VerificationFailed as exc:
        print(f"\nVERIFICATION FAILED: {exc}", file=sys.stderr)
        return FAILED
    finally:
        if args.keep:
            print(f"\nkept: {root} and database {scratch_dsn}")
        else:
            drop_database(dsn, scratch_dsn)
            print("\nscratch database dropped")


def _print_report(report: dict[str, object]) -> None:
    database = report["database"]
    phases = report["phases"]
    ran = [p for p in phases if p["ran"]]

    print("\n" + "=" * 78)
    print("WHAT THE DATABASE HOLDS")
    for name, count in database["counts"].items():
        print(f"  {name:18} {count}")
    print(f"  quality verdicts   {database['quality_verdicts'] or 'none'}")
    print(f"  blurred media      {database['blurred_media']}")

    print("\nWHAT THE API ANSWERED")
    for name, value in report["api"].items():
        print(f"  {name:18} {value}")
    print(f"  audit chain        {report['audit_chain']}")

    print("\nPHASES")
    for phase in sorted(phases, key=lambda p: (len(str(p["phase"])), str(p["phase"]))):
        verdict = "ran" if phase["ran"] else "abstained"
        print(f"  {phase['phase']!s:>4}  {verdict:<9}  "
              f"{phase['artefacts']} artefact(s)")
        if phase["abstained"]:
            print(f"        {phase['abstained'][:88]}")

    print("\n" + "=" * 78)
    print(f"{len(ran)} of {len(phases)} phases ran, {len(phases) - len(ran)} abstained, "
          f"in {report['seconds']}s")
    print("Every figure above is infrastructure validation on generated footage.")
    print("It says the pipeline executes. It says nothing about teaching-behaviour detection.")


if __name__ == "__main__":
    raise SystemExit(main())
