# -*- coding: utf-8 -*-
"""The research questions, held against the proposal that states them and the code that answers.

Two drifts are possible and both are silent. The proposal can reword a question while the system
keeps answering the old one, and the system can delete or rename a module while the declaration
keeps naming it. The first is caught by reading `docs/RESEARCH-SCOPE.md` and comparing; the
second by importing every evidence source. Neither check asserts that a question has been
answered - evidence that exists is not a result, and conflating the two is the defect that makes
`seeded_errors_available: True` mean nothing.

**The scope of record, not the thesis file.** `docs/RESEARCH-SCOPE.md` is generated by
`scripts/extract_scope.py` from the revised proposal and carries that document's digest.
`thesis/02-refined-scope.md` states an earlier design - training on campus microteaching and
evaluating on basic-school classrooms - which the revised proposal replaced with practicum
throughout and a shift axis of held-out schools and colleges. Comparing against the superseded
document would hold the system to questions the candidate no longer asks.

Where the scope file is absent the comparison abstains with a warning rather than passing
quietly, which is the shape `requires_database` uses: "did not run" and "passed" must not be the
same observation.
"""
from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest

from praxis.research import QUESTIONS, EvidenceState, question, resolve

SCOPE = Path(__file__).resolve().parents[2] / "docs" / "RESEARCH-SCOPE.md"
EXPECTED_IDS = ("RQ1", "RQ2", "RQ3", "RQ4", "RQ5", "RQ6")


def scope_rows() -> dict[str, str] | None:
    """The RQ table out of the scope of record, by id, or None when it is not there."""
    if not SCOPE.is_file():
        warnings.warn(
            f"{SCOPE} is not readable, so the declared questions were not compared against "
            f"the proposal's wording. Run scripts/extract_scope.py to regenerate it; a "
            f"missing file means the scope was never extracted, not that the check passed.",
            stacklevel=2)
        return None

    rows = {}
    for line in SCOPE.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\|\s*(RQ[0-9])\s*\|(.+?)\|", line)
        if match:
            rows[match.group(1)] = match.group(2).strip()
    return rows or None


# Written as escapes rather than as the characters themselves: ruff refuses ambiguous unicode
# in source (RUF001), which is the same rule that stops the declaration spelling the proposal's
# apostrophe literally. Folding them here is what lets the two be compared at all.
TYPOGRAPHIC = {
    "\u2018": "'", "\u2019": "'",      # single quotation marks
    "\u201c": '"', "\u201d": '"',      # double quotation marks
    "\u2013": "-", "\u2014": "-",      # en dash and em dash
}


def normalised(text: str) -> str:
    """Formatting removed, so wording is compared and not typography.

    The proposal is a Word document and carries typographic quotes and dashes - "National
    Teachers' Standards" has a right single quotation mark. The declaration spells those ASCII
    because ruff refuses the ambiguous characters in source, so a literal comparison between
    the two would never match on a question that contains one.
    """
    folded = text.replace("**", "").replace("*", "")
    for fancy, plain in TYPOGRAPHIC.items():
        folded = folded.replace(fancy, plain)
    return re.sub(r"\s+", " ", folded).strip()


class TestTheSixAreDeclared:
    def test_all_six_and_no_others(self) -> None:
        assert tuple(q.id for q in QUESTIONS) == EXPECTED_IDS

    def test_each_is_reachable_by_id(self) -> None:
        for question_id in EXPECTED_IDS:
            assert question(question_id).id == question_id

    def test_an_unknown_id_names_the_ones_that_exist(self) -> None:
        with pytest.raises(KeyError, match="RQ1, RQ2, RQ3, RQ4, RQ5, RQ6"):
            question("RQ9")

    def test_every_question_says_what_it_waits_for(self) -> None:
        """A question with nothing blocking it and no evidence would be an empty row."""
        for item in QUESTIONS:
            assert item.evidence or item.blocked_on, (
                f"{item.id} declares neither evidence nor a reason it has none")


class TestTheWordingIsTheProposalWording:
    def test_every_declared_question_appears_in_the_scope_of_record(self) -> None:
        rows = scope_rows()
        if rows is None:
            return

        for item in QUESTIONS:
            assert item.id in rows, (
                f"{item.id} is declared here and absent from {SCOPE.name}")
            assert normalised(item.question) in normalised(rows[item.id]), (
                f"{item.id} is worded differently here than in {SCOPE.name}. The proposal is "
                f"the source; change the declaration, not the proposal.")

    def test_the_proposal_declares_no_question_this_system_ignores(self) -> None:
        rows = scope_rows()
        if rows is None:
            return
        assert set(rows) == set(EXPECTED_IDS)

    def test_the_shift_axis_is_schools_and_colleges_not_a_change_of_domain(self) -> None:
        """The substantive change the revised proposal makes, pinned so it cannot quietly
        revert. RQ3 used to read "trained on campus microteaching ... applied to authentic
        classroom practicum"; it now reads across held-out practicum schools and colleges. The
        system's shift ladder still carries the old labels, which is recorded rather than
        silently patched, and this is the assertion that would fail if the declaration drifted
        back."""
        rq3 = question("RQ3").question.lower()
        assert "held-out practicum schools and colleges" in rq3
        assert "microteaching" not in rq3


class TestEveryEvidenceSourceResolves:
    def test_nothing_declared_is_missing(self) -> None:
        """The check that makes the map fail loudly. A renamed or deleted module breaks this
        rather than leaving a claim standing."""
        broken = {item.id: [e.produced_by for e in item.missing()]
                  for item in QUESTIONS if item.missing()}
        assert not broken, f"declared evidence that does not exist: {broken}"

    def test_a_method_two_levels_deep_resolves(self) -> None:
        """`ReviewSession.adjudicate` is a module, a class and then a function. A resolver that
        split on the last dot reported it missing while it was sitting there."""
        from praxis.research import Evidence
        assert Evidence("x", "praxis.routing.reveal.ReviewSession.adjudicate").state() is (
            EvidenceState.PRESENT)

    @pytest.mark.parametrize("path", [
        "praxis.nonexistent.module",
        "praxis.routing.gate.no_such_function",
        "praxis.routing.reveal.ReviewSession.no_such_method",
    ])
    def test_what_is_absent_reports_absent(self, path) -> None:
        """Negative controls. Without these the check could pass by never failing."""
        from praxis.research import Evidence
        assert Evidence("x", path).state() is EvidenceState.MISSING


class TestTheReportDistinguishesCodeFromResults:
    def test_the_three_unimplemented_questions_say_so(self) -> None:
        """RQ1, RQ4 and RQ6 have no implementation anywhere in this system. They are declared
        with no evidence rather than omitted, because a missing row reads like coverage."""
        unimplemented = {row["id"] for row in resolve() if not row["implemented"]}
        assert unimplemented == {"RQ1", "RQ4", "RQ6"}

    def test_an_unimplemented_question_still_explains_itself(self) -> None:
        for question_id in ("RQ1", "RQ4", "RQ6"):
            assert question(question_id).blocked_on, (
                f"{question_id} has no evidence and no stated reason, which is a blank, not "
                f"an abstention")

    def test_resolve_reports_no_verdict_about_being_answered(self) -> None:
        """Whether code exists and whether it has been run are different facts. Nothing in this
        payload may claim the second."""
        for row in resolve():
            assert set(row) == {"id", "hypotheses", "implemented", "evidence", "missing",
                                "blocked_on"}
            assert "answered" not in row and "result" not in row
