# -*- coding: utf-8 -*-
"""Fixtures shared by the Phase 1 integration tests.

Clips are generated by ffmpeg rather than committed, and their properties are read back off the
file by the code under test rather than asserted from what was requested. A fixture written to
match the implementation proves only that the code agrees with itself.
"""
from __future__ import annotations

import subprocess
import warnings
from datetime import date
from pathlib import Path

import pytest
from sqlalchemy import func

from praxis.config import load_config
from praxis.db import build_engine, keywords_to_url, transaction
from praxis.db.schema import colleges, consent_records, schools, teachers
from praxis.ids import new_ulid
from praxis.tools import resolve

CONFIG = load_config("configs/default.yaml")
FFMPEG = resolve("ffmpeg", CONFIG.tools.ffmpeg)
FFPROBE = resolve("ffprobe", CONFIG.tools.ffprobe)


def requires_database(*resources: object) -> bool:
    """Whether a test needing a database can run. The single place that decides.

    `tests/conftest.py` already makes a *configured but unreachable* database a hard failure, so
    what reaches here is genuinely "none configured". D48: such a check abstains, and the
    abstention is its own verdict - hence a warning rather than a silent pass.

    Neither `pytest.skip` nor a bare `return` is used. The project forbids skip, and a bare
    return makes "this test did not run" and "this test passed" look identical, which is the
    failure mode R1 to R7 exist to prevent. One gate rather than one per call site, because
    seventy guards spelling out the same rule is how sixty-nine of them keep it and one drifts
    (L20). CI supplies a database, so in CI this never fires and the tests genuinely run.
    """
    if all(resource is not None for resource in resources):
        return True
    warnings.warn(
        "this test needs a database and none is configured, so it asserted nothing. Start the "
        "development cluster with: python scripts/dev_services.py start",
        stacklevel=2)
    return False

# 720p so the resolution check passes; duration is set per clip.
WIDTH, HEIGHT, FPS = 1280, 720, 25


def make_clip(path: Path, seconds: float, *, with_audio: bool = True,
              luma: str | None = None, size: str | None = None, rate: int = FPS) -> Path:
    """A synthetic clip whose properties the gate reads back off the file itself.

    `size` and `rate` exist so the duration tests can produce a 20-minute file without encoding
    30,000 frames of 720p. They check the container's duration, which is unaffected.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    source = luma or f"testsrc=size={size or f'{WIDTH}x{HEIGHT}'}:rate={rate}"
    argv = ["-y", "-f", "lavfi", "-i", f"{source}:duration={seconds}"]
    if with_audio:
        argv += ["-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}", "-c:a", "aac"]
    argv += ["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", str(path)]

    done = subprocess.run(FFMPEG.command("-v", "error", *argv, file_only=False),
                          capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=600)
    assert done.returncode == 0, f"could not generate a fixture: {done.stderr[:400]}"
    return path


def lenient(seconds_floor: float = 1.0):
    """The real config with the duration floor lowered, for tests about the other checks."""
    gate = CONFIG.ingest.quality_gate.model_copy(update={"min_duration_s": seconds_floor})
    return CONFIG.model_copy(update={
        "ingest": CONFIG.ingest.model_copy(update={"quality_gate": gate})})


@pytest.fixture
def media_root(tmp_path) -> Path:
    root = tmp_path / "media"
    root.mkdir()
    return root


@pytest.fixture
def engine(scratch_database):
    return build_engine(keywords_to_url(scratch_database)) if scratch_database else None


@pytest.fixture
def party(engine):
    """A college, a school, a teacher and a live consent, so the foreign keys resolve.

    The school is here because a classroom session cannot be written without one -
    `a_classroom_session_names_its_school`, D98 - and most of these tests ingest classroom
    footage. A microteaching test simply passes `school_id=None` and the constraint allows it.
    """
    if engine is None:
        return None
    college, teacher, consent = new_ulid(), new_ulid(), new_ulid()
    school = new_ulid()
    with transaction(engine) as conn:
        conn.execute(colleges.insert().values(
            college_id=college, code=f"COL-{college[-5:]}", created_at=func.now()))
        conn.execute(schools.insert().values(
            school_id=school, code=f"SCH-{school[-5:]}", created_at=func.now()))
        conn.execute(teachers.insert().values(
            teacher_id=teacher, college_id=college, created_at=func.now()))
        conn.execute(consent_records.insert().values(
            consent_id=consent, subject_type="teacher", teacher_id=teacher,
            college_id=college, purpose="research", recipients="supervisors", scope="both",
            granted_on=date(2025, 1, 1), document_ref="file/1", created_at=func.now()))
    return {"college_id": college, "teacher_id": teacher, "consent_id": consent,
            "school_id": school}
