# -*- coding: utf-8 -*-
"""The Phase 3 pipeline end to end, on a real video file.

The video is generated by ffmpeg and decoded by the code under test; the estimator is a test
double. That split is deliberate. Everything the pipeline decides - what to sample, what to
blur, what order to do it in, what to delete - is exercised against real decoding, while the
one component that needs vendored weights is substituted by something whose output is known
exactly. A pose model on a `testsrc` pattern would detect nothing, so a test that used the real
one would assert on an empty pipeline and prove nothing about any of it.

What this therefore does NOT establish: whether YOLOv8-pose finds the people in a Ghanaian
basic-school classroom, or whether the teacher heuristic picks the right person there. Both
need the corpus, and the second needs a human regardless - `require_human_confirmation: true`.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from praxis.preprocess import artifacts
from praxis.preprocess.pipeline import (
    FrameProcessingFailed,
    PreprocessError,
    VideoUnreadable,
    run,
    sample_step,
    teacher_keypoints,
)
from praxis.preprocess.pose import KEYPOINT_COUNT, Detection
from praxis.preprocess.zones import CameraSetup, Polygon
from tests.integration.conftest import FPS, HEIGHT, WIDTH, make_clip

NOSE, LEFT_EYE, RIGHT_EYE = 0, 1, 2
LEFT_SHOULDER, RIGHT_SHOULDER = 5, 6
LEFT_WRIST, RIGHT_WRIST = 9, 10

assert (WIDTH, HEIGHT) == (1280, 720), "the scripted geometry below is in pixels of this clip"

TEACHER_WIDTH, TEACHER_HEIGHT = 140, 400        # near the camera, at the front
LEARNER_WIDTH, LEARNER_HEIGHT = 60, 150         # further away, seated
WALK_PERIOD, WALK_STEP = 16, 30                 # samples per lap, pixels per sample


def _keypoints(x: float, y: float, w: float, h: float, *, hand_up: bool) -> np.ndarray:
    keypoints = np.zeros((KEYPOINT_COUNT, 3), dtype=np.float32)
    cx = x + w / 2
    keypoints[NOSE] = (cx, y + h * 0.08, 0.9)
    keypoints[LEFT_EYE] = (cx - w * 0.12, y + h * 0.06, 0.9)
    keypoints[RIGHT_EYE] = (cx + w * 0.12, y + h * 0.06, 0.9)

    shoulder_y = y + h * 0.25
    keypoints[LEFT_SHOULDER] = (cx - w * 0.3, shoulder_y, 0.9)
    keypoints[RIGHT_SHOULDER] = (cx + w * 0.3, shoulder_y, 0.9)
    keypoints[LEFT_WRIST] = (cx - w * 0.35,
                             shoulder_y - h * 0.15 if hand_up else shoulder_y + h * 0.35, 0.9)
    keypoints[RIGHT_WRIST] = (cx + w * 0.35, shoulder_y + h * 0.35, 0.9)
    return keypoints


class ScriptedEstimator:
    """A `PoseEstimator` whose output is written down rather than inferred.

    One large person walking across the front of the room and two small seated ones, the first
    of whom raises a hand partway through. Which track the heuristic should propose is therefore
    known, which is what makes the assertion about it meaningful.
    """

    model_version = "scripted-double-v1"

    def __init__(self) -> None:
        self.calls = 0

    def detect(self, frame: np.ndarray) -> list[Detection]:
        index = self.calls
        self.calls += 1

        # A triangle wave, so the teacher turns around rather than teleporting back to the
        # start. A modulo wrap would move the box further in one sample than its own width, the
        # tracker would correctly refuse to match it, and the track would fragment - which would
        # be the fixture testing its own arithmetic rather than the pipeline.
        phase = index % WALK_PERIOD
        offset = phase if phase <= WALK_PERIOD // 2 else WALK_PERIOD - phase
        walking_x = 200 + offset * WALK_STEP
        teacher = Detection(
            bbox=(walking_x, 140, walking_x + TEACHER_WIDTH, 140 + TEACHER_HEIGHT),
            keypoints=_keypoints(walking_x, 140, TEACHER_WIDTH, TEACHER_HEIGHT, hand_up=False),
            confidence=0.93)

        learners = []
        for seat, (x, y) in enumerate(((500, 520), (800, 520))):
            hand_up = seat == 0 and index >= 4
            learners.append(Detection(
                bbox=(x, y, x + LEARNER_WIDTH, y + LEARNER_HEIGHT),
                keypoints=_keypoints(x, y, LEARNER_WIDTH, LEARNER_HEIGHT, hand_up=hand_up),
                confidence=0.81))
        return [teacher, *learners]


class BlindEstimator:
    """Detects nothing, which is a legitimate outcome and must not be a crash."""

    model_version = "blind-double-v1"

    def detect(self, frame: np.ndarray) -> list[Detection]:
        return []


class BrokenEstimator:
    model_version = "broken-double-v1"

    def detect(self, frame: np.ndarray) -> list[Detection]:
        raise RuntimeError("the model refused this frame")


def band(top: float, bottom: float) -> Polygon:
    return Polygon(((0.0, top), (1.0, top), (1.0, bottom), (0.0, bottom)))


@pytest.fixture
def setup() -> CameraSetup:
    """Front band covers the teacher's walking line; learners sit in middle and back."""
    return CameraSetup(
        setup_id="01" + "0" * 24, zone_board=band(0.0, 0.15), zone_front=band(0.15, 0.7),
        zone_middle=band(0.7, 0.85), zone_back=band(0.85, 1.0),
        learner_region=band(0.7, 1.0))


@pytest.fixture
def paths(tmp_path: Path) -> dict[str, Path]:
    return {"source": tmp_path / "incoming" / "session.mp4",
            "blurred": tmp_path / "media" / "session.blurred.mp4",
            "pose": tmp_path / "pose" / "session.npz"}


SYNTHETIC_SESSION = "01" + "0" * 24


def preprocess(paths, config, estimator, setup, seconds: float = 2.0,
               session_id: str = SYNTHETIC_SESSION, **kwargs):
    make_clip(paths["source"], seconds)
    return run(session_id=session_id, source=paths["source"],
               blurred_destination=paths["blurred"], pose_output=paths["pose"],
               estimator=estimator, config=config, setup=setup, **kwargs)


# ---------------------------------------------------------------------------
# The six steps, in the order that is a privacy requirement
# ---------------------------------------------------------------------------

def test_the_original_does_not_survive_preprocessing(paths, config, setup) -> None:
    """The deletion BUILD-SPEC calls non-negotiable, verified against the filesystem."""
    result = preprocess(paths, config, ScriptedEstimator(), setup)

    assert not paths["source"].exists()
    assert result.original_deleted
    assert paths["blurred"].is_file() and paths["blurred"].stat().st_size > 0


def test_pose_runs_before_the_faces_are_destroyed(paths, config, setup) -> None:
    """The order is the whole design: the estimator must see every sampled frame, and the
    blurred output must be a different file from the one it saw."""
    estimator = ScriptedEstimator()
    result = preprocess(paths, config, estimator, setup)

    assert estimator.calls == result.frames_processed > 0
    assert result.faces_blurred > 0
    assert paths["blurred"].resolve() != paths["source"].resolve()


def test_every_decoded_frame_is_written_to_the_blurred_video(paths, config, setup) -> None:
    """Sampling controls what pose sees, not what survives. A blurred video shorter than the
    original would be a different recording of the lesson."""
    import cv2

    seconds = 2.0
    make_clip(paths["source"], seconds)
    capture = cv2.VideoCapture(str(paths["source"]))
    original_frames = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
    capture.release()

    run(session_id="01" + "0" * 24, source=paths["source"],
        blurred_destination=paths["blurred"], pose_output=paths["pose"],
        estimator=ScriptedEstimator(), config=config, setup=setup)

    capture = cv2.VideoCapture(str(paths["blurred"]))
    written = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
    capture.release()

    assert written == original_frames


def test_the_sampling_rate_is_the_configured_one(paths, config, setup) -> None:
    result = preprocess(paths, config, ScriptedEstimator(), setup, seconds=2.0)

    assert result.artifact.sampled_fps == config.preprocess.sample_fps
    expected = int(2.0 * FPS / sample_step(FPS, config.preprocess.sample_fps))
    assert abs(result.frames_processed - expected) <= 1


def test_sampling_is_deterministic() -> None:
    """R7. The step depends only on the two rates, so two runs of the same configuration select
    the same frames."""
    assert sample_step(25.0, 8.0) == pytest.approx(3.125)
    assert sample_step(8.0, 8.0) == 1.0
    assert sample_step(4.0, 8.0) == 1.0, "never invent frames the source does not have"
    with pytest.raises(VideoUnreadable):
        sample_step(0.0, 8.0)


# ---------------------------------------------------------------------------
# What the pipeline produces
# ---------------------------------------------------------------------------
def test_two_runs_of_one_configuration_produce_the_same_artefact(paths, config,
                                                                 setup) -> None:
    """R7, end to end. Same video, same configuration, same bytes - so the hash in
    `pose_artifacts` identifies the preprocessing, not the occasion it was run on."""
    first = preprocess(paths, config, ScriptedEstimator(), setup)
    second = preprocess(paths, config, ScriptedEstimator(), setup)

    assert second.artifact.sha256 == first.artifact.sha256
    assert second.artifact.config_sha256 == first.artifact.config_sha256
    assert second.frames_processed == first.frames_processed
    assert second.proposal.track_id == first.proposal.track_id



def test_the_artefact_holds_every_sampled_frame_and_verifies(paths, config, setup) -> None:
    result = preprocess(paths, config, ScriptedEstimator(), setup)
    artifact = result.artifact

    assert artifact.frame_count == result.frames_processed
    assert artifact.max_persons == 3
    assert artifact.model_version == "scripted-double-v1"

    loaded = artifacts.load(paths["pose"], artifact.sha256)
    assert loaded.keypoints.shape == (artifact.frame_count, 3, KEYPOINT_COUNT, 3)
    assert loaded.provenance["config_sha256"] == artifact.config_sha256
    assert set(loaded.person_count.tolist()) == {3}


def test_the_teacher_track_is_proposed_and_left_unconfirmed(paths, config, setup) -> None:
    """The scripted teacher is present throughout, largest, and in the front zone, so the
    heuristic should name that track. It still may not confirm it."""
    result = preprocess(paths, config, ScriptedEstimator(), setup)
    proposal = result.proposal

    assert proposal.track_id is not None
    assert not proposal.is_confirmed
    row = proposal.as_row(source="detection", limit=20)
    assert row["confirmed_by"] is None
    # The ranking the reviewer is shown reaches the row, which before 0009 it did not.
    assert row["reason"] == proposal.reason
    assert [c["track_id"] for c in row["candidates"]["ranked"]] == [
        s.track_id for s in proposal.signals]

    keypoints = teacher_keypoints(paths["pose"], proposal.track_id, result.artifact.sha256)
    assert keypoints.shape == (result.artifact.frame_count, KEYPOINT_COUNT, 3)

    # The proposed track is the physically largest one, which is what the weights encode.
    ranked = sorted(proposal.signals, key=lambda s: s.median_area_fraction, reverse=True)
    assert ranked[0].track_id == proposal.track_id


def test_learner_bins_count_the_learners_and_not_the_teacher(paths, config, setup) -> None:
    result = preprocess(paths, config, ScriptedEstimator(), setup, learner_bin_seconds=10.0)

    assert result.learner_bins, "a two-second session still produces one bin"
    total = result.learner_bins[0]
    assert total.person_count == 2, "two seated learners; the proposed teacher is excluded"
    assert total.hands_raised == 1, "one learner raises one hand, once"


def test_a_learner_bin_reaches_the_database_row_without_an_identifier(paths, config,
                                                                     setup) -> None:
    """R1 at the boundary: what `summarise` hands to the writer has no column for a person."""
    result = preprocess(paths, config, ScriptedEstimator(), setup)
    row = result.learner_bins[0].as_row("01" + "0" * 24)

    assert set(row) == {"session_id", "t_start_s", "hands_raised", "gross_motion",
                        "person_count"}


def test_an_empty_room_produces_an_artefact_and_no_proposal(paths, config, setup) -> None:
    """Nothing detected is a real outcome. It must not crash, and it must not propose a
    teacher out of an empty frame."""
    result = preprocess(paths, config, BlindEstimator(), setup)

    assert result.frames_processed > 0
    assert result.faces_blurred == 0
    assert result.proposal.track_id is None
    assert result.learner_bins[0].person_count == 0
    assert not paths["source"].exists(), "the original still goes, whatever was in it"

    loaded = artifacts.load(paths["pose"], result.artifact.sha256)
    assert loaded.keypoints.shape[1] == 0
    assert set(loaded.person_count.tolist()) == {0}


def test_a_session_without_zones_still_runs_and_says_so(paths, config) -> None:
    """An unmarked setup weakens the heuristic and must say so rather than score as if the
    front-zone term had been measured and found to be zero."""
    result = preprocess(paths, config, ScriptedEstimator(), None)

    assert not result.zones_available
    assert "not comparable" in result.proposal.reason
    # Excluding the teacher is by identity, not by zone, so it survives having no zones.
    assert result.learner_bins[0].person_count == 2


# ---------------------------------------------------------------------------
# Failure leaves the original intact
# ---------------------------------------------------------------------------

def test_a_pose_failure_is_raised_and_the_original_is_kept(paths, config, setup) -> None:
    """A failure before deletion is recoverable; the session can be reprocessed. That is why
    deletion is last."""
    make_clip(paths["source"], 1.0)

    with pytest.raises(FrameProcessingFailed, match="pose estimation failed"):
        run(session_id="01" + "0" * 24, source=paths["source"],
            blurred_destination=paths["blurred"], pose_output=paths["pose"],
            estimator=BrokenEstimator(), config=config, setup=setup)

    assert paths["source"].is_file(), "nothing was deleted, so nothing was lost"


def test_an_undecodable_file_is_refused_before_anything_is_deleted(paths, config,
                                                                   setup) -> None:
    paths["source"].parent.mkdir(parents=True, exist_ok=True)
    paths["source"].write_bytes(b"this is not an mp4")

    with pytest.raises(PreprocessError):
        run(session_id="01" + "0" * 24, source=paths["source"],
            blurred_destination=paths["blurred"], pose_output=paths["pose"],
            estimator=ScriptedEstimator(), config=config, setup=setup)

    assert paths["source"].is_file()
