# -*- coding: utf-8 -*-
"""Phase 1 end to end, against a real database and real video.

The fixtures are generated by ffmpeg rather than committed, and their properties are read back
from the file rather than assumed. A fixture written to match the implementation would prove
only that the code agrees with itself, which is how this project has twice shipped a defect that
every local reading made look correct.

The four acceptance tests BUILD-SPEC names for this phase are at the bottom, marked.

Video generation is slow, so the clips are session-scoped and the gate thresholds are lowered
for the tests that do not care about duration. The duration thresholds themselves are exercised
against the real configured values, because that is the check being tested.
"""
from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

import pytest
from sqlalchemy import func, select

from praxis.audit.chain import verify
from praxis.audit.write import read_chain
from praxis.db import sessions, transaction
from praxis.db.schema import audit_log, media_objects
from praxis.ids import new_ulid
from praxis.ingest import probe as probe_module
from praxis.ingest.errors import IngestRefused
from praxis.ingest.probe import mean_luminance
from praxis.ingest.service import IngestRequest, ingest
from praxis.ingest.storage import TEMP_SUBDIR, read_in_chunks
from praxis.tasks import RecordingQueue
from tests.integration.conftest import (
    CONFIG,
    FFMPEG,
    FFPROBE,
    FPS,
    HEIGHT,
    WIDTH,
    lenient,
    make_clip,
    requires_database,
)


@pytest.fixture(scope="session")
def clips(tmp_path_factory) -> dict[str, Path]:
    root = tmp_path_factory.mktemp("clips")
    return {
        "good": make_clip(root / "good.mp4", 6.0),
        "silent": make_clip(root / "silent.mp4", 6.0, with_audio=False),
        "dark": make_clip(root / "dark.mp4", 6.0,
                          luma="color=c=black:size=1280x720:rate=25"),
        "corrupt": _corrupt(root / "corrupt.mp4"),
    }


def _corrupt(path: Path) -> Path:
    """Not a video. ffprobe must refuse it with a reason rather than a traceback.

    Plain ASCII with no container header rather than random bytes: the point is that
    ffprobe can find no format at all, and a deterministic payload means a failure here
    is always the same failure.
    """
    path.write_bytes(b"this file claims to be an mp4 and is not" * 512)
    return path


def request_for(clip: Path, party: dict, **overrides) -> IngestRequest:
    base = dict(
        filename=clip.name, chunks=read_in_chunks(clip, CONFIG.ingest.hash_chunk_bytes),
        teacher_id=party["teacher_id"], college_id=party["college_id"],
        consent_id=party["consent_id"], domain="classroom", school_id=party["school_id"],
        recorded_on=date(2026, 5, 4),
        subject="integrated science", actor_role="researcher")
    base.update(overrides)
    return IngestRequest(**base)


def run(request, engine, media_root, config=None, queue=None):
    return ingest(request, engine=engine, config=config or lenient(),
                  ffprobe=FFPROBE, ffmpeg=FFMPEG, media_root=media_root,
                  enqueue=queue or RecordingQueue())


def rows(engine, table, where=None) -> int:
    statement = select(func.count()).select_from(table)
    if where is not None:
        statement = statement.where(where)
    with transaction(engine) as conn:
        return conn.execute(statement).scalar()


# ---------------------------------------------------------------------------
# Frame rate
# ---------------------------------------------------------------------------

def mixed_rate_clip(path: Path, fast_fps: int, slow_fps: int, half: float) -> Path:
    """One stream carrying two frame rates, which is what a phone recording is.

    `r_frame_rate` becomes the least common multiple of the two and overstates the file;
    `avg_frame_rate` is the frame count over the duration and describes it.
    """
    argv = ["-y",
            "-f", "lavfi", "-i", f"testsrc=size={WIDTH}x{HEIGHT}:rate={fast_fps}:d={half}",
            "-f", "lavfi", "-i", f"testsrc=size={WIDTH}x{HEIGHT}:rate={slow_fps}:d={half}",
            "-filter_complex", "[0:v][1:v]concat=n=2:v=1[out]", "-map", "[out]",
            "-fps_mode", "vfr",
            "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", str(path)]
    done = subprocess.run(FFMPEG.command("-v", "error", *argv, file_only=False),
                          capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=600)
    assert done.returncode == 0, f"could not generate a fixture: {done.stderr[:400]}"
    return path


def test_the_frame_rate_is_what_the_file_delivers_not_what_its_timebase_allows(
        tmp_path) -> None:
    """Half at 30 fps and half at 10 is a 20 fps recording. `r_frame_rate` calls it 30, which is
    above the configured floor, so the check used to pass a file it exists to refuse. D79."""
    clip = mixed_rate_clip(tmp_path / "mixed.mp4", fast_fps=30, slow_fps=10, half=3.0)
    metadata = probe_module.probe(FFPROBE, clip)

    assert metadata.fps == pytest.approx(20.0, abs=0.5)
    assert metadata.fps < CONFIG.ingest.quality_gate.min_fps


def test_a_recording_too_choppy_for_the_gate_is_refused(tmp_path) -> None:
    """The check and the number it reads, together. Duration is lowered so this fails on the
    frame rate and nothing else."""
    clip = mixed_rate_clip(tmp_path / "choppy.mp4", fast_fps=30, slow_fps=10, half=3.0)
    gate = lenient().ingest.quality_gate

    metadata = probe_module.probe(FFPROBE, clip)
    report = probe_report(metadata, gate, clip)

    assert report.verdict == "fail"
    assert any(c.name == "frame_rate" for c in report.failures), report.reason()


def probe_report(metadata, gate, clip: Path):
    from praxis.ingest.quality import evaluate

    return evaluate(metadata, gate,
                    fps_jitter=probe_module.frame_rate_jitter(FFPROBE, clip),
                    mean_luma=mean_luminance(FFMPEG, clip, gate.person_detection_sample_frames,
                                             metadata.duration_s),
                    person_fraction=None)


def test_a_steady_recording_reports_the_rate_it_was_made_at(tmp_path) -> None:
    """The fallback must not cost accuracy on ordinary constant-rate footage."""
    metadata = probe_module.probe(FFPROBE, make_clip(tmp_path / "steady.mp4", 4.0))
    assert metadata.fps == pytest.approx(float(FPS), abs=0.3)


# ---------------------------------------------------------------------------
# Brightness sampling
#
# The gate's luminance check reads frames from across the file. These tests are about *which*
# frames it reaches, because a sampler that silently only ever read the opening seconds would
# still return a plausible number for every clip above.
# ---------------------------------------------------------------------------

def two_tone_clip(path: Path, seconds: float) -> Path:
    """Black for the first half, white for the second. Its mean luminance is near the middle.

    A clip whose brightness is uniform cannot distinguish a sampler that spans the file from one
    that reads the first frame N times, and that is the distinction being tested.
    """
    half = seconds / 2
    argv = ["-y",
            "-f", "lavfi", "-i", f"color=c=black:size={WIDTH}x{HEIGHT}:rate={FPS}:d={half}",
            "-f", "lavfi", "-i", f"color=c=white:size={WIDTH}x{HEIGHT}:rate={FPS}:d={half}",
            "-filter_complex", "[0:v][1:v]concat=n=2:v=1[out]", "-map", "[out]",
            "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", str(path)]
    done = subprocess.run(FFMPEG.command("-v", "error", *argv, file_only=False),
                          capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=600)
    assert done.returncode == 0, f"could not generate a fixture: {done.stderr[:400]}"
    return path


def test_brightness_is_sampled_across_the_file_not_from_its_opening(tmp_path) -> None:
    """The measurement is the mean over frames spread through the recording. Half black and half
    white therefore reads mid-grey; a sampler stuck at the start would read near zero."""
    clip = two_tone_clip(tmp_path / "two_tone.mp4", 8.0)
    observed = mean_luminance(FFMPEG, clip, sample_frames=24, duration_s=8.0)
    assert 96 < observed < 160, f"mean luminance {observed} is not mid-scale"


def test_brightness_does_not_depend_on_how_long_the_recording_is(tmp_path) -> None:
    """The same content at two lengths is the same brightness. This is what changed when the
    sampler stopped decoding the whole file and started seeking: the measurement had to stay
    put while the mechanism moved. D78."""
    short = mean_luminance(FFMPEG, two_tone_clip(tmp_path / "short.mp4", 4.0),
                           sample_frames=24, duration_s=4.0)
    longer = mean_luminance(FFMPEG, two_tone_clip(tmp_path / "long.mp4", 20.0),
                            sample_frames=24, duration_s=20.0)
    assert abs(short - longer) < 12


def test_a_black_clip_and_a_white_clip_are_told_apart(tmp_path, clips) -> None:
    white = make_clip(tmp_path / "white.mp4", 4.0,
                      luma=f"color=c=white:size={WIDTH}x{HEIGHT}:rate={FPS}")
    dark = mean_luminance(FFMPEG, clips["dark"], sample_frames=12, duration_s=6.0)
    bright = mean_luminance(FFMPEG, white, sample_frames=12, duration_s=4.0)
    assert dark < 32 < 224 < bright


def test_a_sampling_timeout_is_a_refusal_rather_than_a_subprocess_error(tmp_path,
                                                                       monkeypatch) -> None:
    """Every ffmpeg call in this module goes through `_run` so that a timeout becomes an
    `IngestRefused` the service can record. The brightness sampler used to call
    `subprocess.run` itself, so a long recording ended the ingest request with a raw
    `TimeoutExpired` and nothing in the audit trail said why. D78."""
    clip = make_clip(tmp_path / "plain.mp4", 2.0)

    def always_times_out(*args, **kwargs):
        raise subprocess.TimeoutExpired(cmd="ffmpeg", timeout=1)

    monkeypatch.setattr(probe_module.subprocess, "run", always_times_out)

    with pytest.raises(IngestRefused, match="could not be read within"):
        mean_luminance(FFMPEG, clip, sample_frames=4, duration_s=2.0)


def test_an_undecodable_sample_point_is_skipped_but_a_whole_bad_file_is_refused(clips) -> None:
    """A seek landing in a damaged region contributes nothing and the remaining samples still
    produce a measurement. A file with no decodable frame anywhere is a refusal."""
    with pytest.raises(IngestRefused, match="brightness"):
        mean_luminance(FFMPEG, clips["corrupt"], sample_frames=4, duration_s=6.0)

    # zero samples requested is not a failure to decode; it is nothing asked for
    assert mean_luminance(FFMPEG, clips["good"], sample_frames=0, duration_s=6.0) == 0.0
    assert mean_luminance(FFMPEG, clips["good"], sample_frames=4, duration_s=0.0) == 0.0


# ---------------------------------------------------------------------------
# The happy path, and what it writes
# ---------------------------------------------------------------------------

def test_a_good_upload_becomes_a_session(engine, party, clips, media_root) -> None:
    if not requires_database(engine):
        return

    queue = RecordingQueue()
    result = run(request_for(clips["good"], party), engine, media_root, queue=queue)

    assert result.quality.verdict in ("pass", "warn")
    assert result.session.media_sha256 == result.media.media_sha256
    assert result.media.absolute(media_root).is_file()
    assert queue.delivered == [result.session.session_id], (
        "the queue is handed the session id, once, after the commit")

    with transaction(engine) as conn:
        stored = conn.execute(select(sessions).where(
            sessions.c.session_id == result.session.session_id)).mappings().one()
    assert stored["quality_verdict"] == result.quality.verdict
    assert set(stored["quality_detail"]) == {c.name for c in result.quality.checks}


def test_the_session_and_its_audit_row_commit_together(engine, party, clips,
                                                      media_root) -> None:
    """D47. The trail and the facts cannot disagree, so they are one transaction."""
    if not requires_database(engine):
        return

    result = run(request_for(clips["good"], party), engine, media_root)
    with transaction(engine) as conn:
        chain = read_chain(conn)
        ingested = [r for r in chain if r.entity_id == result.session.session_id]

    assert len(ingested) == 1
    assert ingested[0].event_type == "session.ingested"
    assert ingested[0].payload["teacher_id"] == party["teacher_id"]
    assert ingested[0].row_hash == result.audit_row_hash
    assert verify(chain) is None


def test_the_person_check_abstains_rather_than_passing(engine, party, clips,
                                                       media_root) -> None:
    """D48. No detector weights are vendored, and a check that did not run must not report the
    same verdict as one that ran and succeeded."""
    if not requires_database(engine):
        return

    result = run(request_for(clips["good"], party), engine, media_root)
    person = result.quality.as_detail()["person_present"]
    assert person["verdict"] == "abstain"
    assert "D48" in person["detail"]


def test_a_silent_recording_warns_rather_than_failing(engine, party, clips, media_root) -> None:
    """Audio drives learner-response events only, so its absence costs a feature, not the
    session."""
    if not requires_database(engine):
        return

    result = run(request_for(clips["silent"], party), engine, media_root)
    assert result.quality.as_detail()["audio"]["verdict"] == "warn"
    assert result.quality.verdict == "warn"


def test_a_dark_recording_fails_and_is_still_recorded(engine, party, clips,
                                                      media_root) -> None:
    """D45: a gate failure is a verdict, not a refusal. The row exists, marked."""
    if not requires_database(engine):
        return

    result = run(request_for(clips["dark"], party), engine, media_root)
    assert result.quality.as_detail()["luminance"]["verdict"] == "fail"
    assert result.quality.verdict == "fail"

    with transaction(engine) as conn:
        stored = conn.execute(select(sessions.c.quality_verdict).where(
            sessions.c.session_id == result.session.session_id)).scalar()
    assert stored == "fail", "D45: a failed session is recorded so Phase 4 can exclude it"


# ---------------------------------------------------------------------------
# BUILD-SPEC Phase 1 acceptance tests
# ---------------------------------------------------------------------------

def test_acceptance_upload_without_valid_consent_stores_no_bytes_and_no_rows(
        engine, party, clips, media_root) -> None:
    if not requires_database(engine):
        return

    before = (rows(engine, sessions), rows(engine, media_objects))
    with pytest.raises(IngestRefused) as refused:
        run(request_for(clips["good"], party, consent_id=new_ulid()), engine, media_root)

    assert refused.value.refusal.status == 422
    assert refused.value.refusal.slug == "consent-invalid"
    assert (rows(engine, sessions), rows(engine, media_objects)) == before
    assert list(media_root.rglob("*.mp4")) == [], "R: a refused upload wrote bytes"
    assert list((media_root / TEMP_SUBDIR).glob("*.part")) == []

    # The refusal is still in the trail; that is what an audit is for.
    with transaction(engine) as conn:
        rejected = conn.execute(select(func.count()).select_from(audit_log).where(
            audit_log.c.event_type == "session.rejected")).scalar()
    assert rejected >= 1


def test_acceptance_the_same_file_twice_deduplicates_to_one_media_object(
        engine, party, clips, media_root) -> None:
    """One media object, two sessions permitted - the second under a different date, since the
    same file for the same teacher on the same day is a duplicate click. D51."""
    if not requires_database(engine):
        return

    first = run(request_for(clips["good"], party), engine, media_root)
    second = run(request_for(clips["good"], party, recorded_on=date(2026, 5, 5)),
                 engine, media_root)

    assert first.media.media_sha256 == second.media.media_sha256
    assert second.media.deduplicated and not first.media.deduplicated
    assert first.session.session_id != second.session.session_id

    # Counted by hash rather than by table, because the scratch database is shared across the
    # module and a global count would be asserting about the other tests.
    digest = first.media.media_sha256
    mine = (sessions.c.media_sha256 == digest) & (sessions.c.teacher_id == party["teacher_id"])
    assert rows(engine, media_objects, media_objects.c.media_sha256 == digest) == 1
    assert rows(engine, sessions, mine) == 2
    assert len(list((media_root / "media").rglob("*.mp4"))) == 1


def test_acceptance_a_duplicate_upload_is_refused(engine, party, clips, media_root) -> None:
    """Same hash, same teacher, same date. Refused by the constraint, not by a prior SELECT,
    because check-then-insert is a race. D51."""
    if not requires_database(engine):
        return

    first = run(request_for(clips["good"], party), engine, media_root)
    with pytest.raises(IngestRefused) as refused:
        run(request_for(clips["good"], party), engine, media_root)

    assert refused.value.refusal.status == 409
    assert rows(engine, sessions,
                (sessions.c.media_sha256 == first.media.media_sha256)
                & (sessions.c.teacher_id == party["teacher_id"])) == 1


def test_acceptance_a_corrupt_mp4_fails_with_a_reason_not_a_stack_trace(
        engine, party, clips, media_root) -> None:
    if not requires_database(engine):
        return

    before = (rows(engine, sessions), rows(engine, media_objects))
    with pytest.raises(IngestRefused) as refused:
        run(request_for(clips["corrupt"], party), engine, media_root)

    problem = refused.value.refusal
    assert problem.status == 422 and problem.slug == "media-unreadable"
    assert problem.detail and "Traceback" not in problem.detail
    assert (rows(engine, sessions), rows(engine, media_objects)) == before, (
        "D45: an unreadable file cannot be recorded, because media_objects requires a duration")


def test_acceptance_a_clip_below_the_duration_floor_fails_and_one_above_passes(
        engine, party, media_root, tmp_path) -> None:
    """The one test that uses the real configured thresholds, since they are what it checks.

    BUILD-SPEC phrased this as "three minutes fails and twenty passes", which was the 300-second
    floor written into the assertion. That floor is now derived from the clip length and stands
    at 40 seconds (D81), and a test naming the old number would have gone on passing while
    describing a gate that no longer exists. The durations come from the configuration instead,
    so this keeps testing the floor rather than a particular value of it.

    The frame size is the smallest the resolution check accepts, which keeps the encode cheap
    while still clearing the gate the duration check is being isolated from.
    """
    if not requires_database(engine):
        return

    floor = CONFIG.ingest.quality_gate.min_duration_s
    cheap = {"with_audio": False, "size": "512x288", "rate": 2}
    short = make_clip(tmp_path / "under.mp4", max(1.0, floor - 10.0), **cheap)
    long_enough = make_clip(tmp_path / "over.mp4", floor + 60.0, **cheap)

    under = run(request_for(short, party), engine, media_root, config=CONFIG)
    over = run(request_for(long_enough, party, recorded_on=date(2026, 5, 6)),
               engine, media_root, config=CONFIG)

    assert under.quality.as_detail()["duration"]["verdict"] == "fail"
    assert under.quality.verdict == "fail"
    assert over.quality.as_detail()["duration"]["verdict"] == "pass"
    assert over.quality.as_detail()["resolution"]["verdict"] == "pass", (
        "the fixture must clear the resolution gate, or this is not isolating duration")


# ---------------------------------------------------------------------------
# Geometry under rotation
#
# Half the real corpus is portrait phone video and two files carry a -90 display matrix. The
# decoder applies that rotation; what the record must not do is describe the stream instead of
# the frames the pipeline will see. D80, D81.
# ---------------------------------------------------------------------------

def rotated_clip(path: Path, seconds: float, degrees: int) -> Path:
    """A clip carrying a display matrix, written the way a phone writes one.

    Two steps because `-display_rotation` is an input option: encode plainly, then remux with
    the rotation applied and the stream copied, which is what a container with a rotated
    display matrix and unrotated pixels actually looks like.
    """
    plain = path.with_name(f"plain-{path.name}")
    make_clip(plain, seconds, with_audio=False, size="640x360", rate=5)
    done = subprocess.run(
        FFMPEG.command("-v", "error", "-y", "-display_rotation", str(degrees),
                       "-i", str(plain), "-c", "copy", str(path), file_only=False),
        capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=600)
    assert done.returncode == 0, f"could not rotate a fixture: {done.stderr[:400]}"
    return path


@pytest.mark.parametrize("degrees", [90, 270])
def test_the_recorded_geometry_is_what_the_decoder_produces(tmp_path, degrees) -> None:
    """A quarter turn swaps the axes. Recording 640x360 for a file that decodes to 360x640
    would describe a landscape recording that does not exist, and the resolution check would
    then be testing the wrong edge. D80."""
    import cv2

    clip = rotated_clip(tmp_path / f"r{degrees}.mp4", 2.0, degrees)
    metadata = probe_module.probe(FFPROBE, clip)

    capture = cv2.VideoCapture(str(clip))
    ok, frame = capture.read()
    capture.release()
    assert ok

    assert metadata.rotation_degrees == degrees
    assert (metadata.width, metadata.height) == (frame.shape[1], frame.shape[0])
    assert metadata.is_portrait and metadata.orientation == "portrait"


def test_an_unrotated_recording_is_unaffected(tmp_path) -> None:
    metadata = probe_module.probe(FFPROBE, make_clip(tmp_path / "flat.mp4", 2.0))
    assert metadata.rotation_degrees == 0
    assert metadata.orientation == "landscape"
    assert (metadata.width, metadata.height) == (WIDTH, HEIGHT)


def test_portrait_and_landscape_of_the_same_size_are_judged_alike(tmp_path) -> None:
    """D81. The gate measures frame area and shorter edge, not width and height. 360x640 and
    640x360 hold the same amount of teacher and letterbox into the same square, so a width
    threshold would accept one and refuse the other for no reason that survives stating."""
    gate = CONFIG.ingest.quality_gate
    landscape = probe_module.probe(FFPROBE, make_clip(tmp_path / "land.mp4", 2.0,
                                                      with_audio=False, size="640x360", rate=5))
    portrait = probe_module.probe(FFPROBE, rotated_clip(tmp_path / "port.mp4", 2.0, 90))

    assert landscape.pixels == portrait.pixels
    assert landscape.shorter_edge == portrait.shorter_edge

    def accepted(m) -> bool:
        return m.pixels >= gate.min_frame_pixels and m.shorter_edge >= gate.min_shorter_edge

    assert accepted(landscape) == accepted(portrait)


def test_a_frame_too_small_to_pose_is_still_refused(tmp_path) -> None:
    """Relaxing the resolution gate for portrait footage must not relax it into nothing."""
    gate = CONFIG.ingest.quality_gate
    tiny = probe_module.probe(FFPROBE, make_clip(tmp_path / "tiny.mp4", 2.0, with_audio=False,
                                                 size="160x120", rate=5))
    assert tiny.pixels < gate.min_frame_pixels
    assert tiny.shorter_edge < gate.min_shorter_edge


def test_a_wide_strip_is_refused_on_its_shorter_edge(tmp_path) -> None:
    """Area alone is not enough. A very wide, very short frame can clear the pixel floor while
    leaving a standing teacher a few dozen pixels tall once letterboxed into the pose square."""
    gate = CONFIG.ingest.quality_gate
    strip = probe_module.probe(FFPROBE, make_clip(tmp_path / "strip.mp4", 2.0, with_audio=False,
                                                  size="1920x96", rate=5))
    assert strip.pixels >= gate.min_frame_pixels, "the fixture must clear the area floor"
    assert strip.shorter_edge < gate.min_shorter_edge, "and be refused on its shorter edge"
